# Generated by Django 5.0.4 on 2024-11-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "license_type",
                    models.CharField(
                        choices=[("Software", "Software"), ("Hardware", "Hardware")],
                        max_length=255,
                    ),
                ),
                ("vendor", models.CharField(max_length=255)),
                ("license_key", models.CharField(max_length=255, unique=True)),
                ("pucharse_date", models.DateField()),
                ("expiration_date", models.DateField()),
                ("renewal_terms", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
